// Code generated by sqlc. DO NOT EDIT.

package turnips

import (
	"database/sql"
	"fmt"
	"time"
)

type Meridiem string

const (
	MeridiemAm Meridiem = "am"
	MeridiemPm Meridiem = "pm"
)

func (e *Meridiem) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Meridiem(s)
	case string:
		*e = Meridiem(s)
	default:
		return fmt.Errorf("unsupported scan type for Meridiem: %T", src)
	}
	return nil
}

type Price struct {
	ID        int64     `json:"id"`
	DiscordID string    `json:"discord_id"`
	Price     int32     `json:"price"`
	Meridiem  Meridiem  `json:"meridiem"`
	DayOfWeek int32     `json:"day_of_week"`
	DayOfYear int32     `json:"day_of_year"`
	Year      int32     `json:"year"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID         int64          `json:"id"`
	Username   string         `json:"username"`
	DiscordID  string         `json:"discord_id"`
	FriendCode sql.NullString `json:"friend_code"`
	TimeZone   string         `json:"time_zone"`
}
