// Code generated by sqlc. DO NOT EDIT.

package turnips

import (
	"context"
)

type Querier interface {
	CountPricesByDiscordId(ctx context.Context, discordID string) (int64, error)
	CountUsersByDiscordId(ctx context.Context, discordID string) (int64, error)
	CreatePrice(ctx context.Context, arg CreatePriceParams) (Price, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePricesForUser(ctx context.Context, discordID string) error
	DeleteUser(ctx context.Context, discordID string) error
	GetUsers(ctx context.Context, discordID string) (User, error)
	GetWeeksPriceHistoryByUser(ctx context.Context, discordID string) ([]Price, error)
	ListPrices(ctx context.Context) ([]Price, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateFriendCode(ctx context.Context, arg UpdateFriendCodeParams) (User, error)
	UpdateTimeZone(ctx context.Context, arg UpdateTimeZoneParams) (User, error)
}

var _ Querier = (*Queries)(nil)
