// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package turnips

import (
	"context"
	"database/sql"
)

const countUsersByDiscordId = `-- name: CountUsersByDiscordId :one
SELECT count(*)
FROM users
where discord_id = $1
`

func (q *Queries) CountUsersByDiscordId(ctx context.Context, discordID string) (int64, error) {
	row := q.queryRow(ctx, q.countUsersByDiscordIdStmt, countUsersByDiscordId, discordID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, discord_id)
VALUES ($1, $2)
RETURNING id, username, discord_id, friend_code
`

type CreateUserParams struct {
	Username  string `json:"username"`
	DiscordID string `json:"discord_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.DiscordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DiscordID,
		&i.FriendCode,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM users
WHERE discord_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, discordID string) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, discordID)
	return err
}

const getUsers = `-- name: GetUsers :one
SELECT id, username, discord_id, friend_code
FROM users
WHERE discord_id = $1
LIMIT 1
`

func (q *Queries) GetUsers(ctx context.Context, discordID string) (User, error) {
	row := q.queryRow(ctx, q.getUsersStmt, getUsers, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DiscordID,
		&i.FriendCode,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, discord_id, friend_code
FROM users
ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DiscordID,
			&i.FriendCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendCode = `-- name: UpdateFriendCode :one
UPDATE users
set friend_code = $1
where discord_id = $2
RETURNING id, username, discord_id, friend_code
`

type UpdateFriendCodeParams struct {
	FriendCode sql.NullString `json:"friend_code"`
	DiscordID  string         `json:"discord_id"`
}

func (q *Queries) UpdateFriendCode(ctx context.Context, arg UpdateFriendCodeParams) (User, error) {
	row := q.queryRow(ctx, q.updateFriendCodeStmt, updateFriendCode, arg.FriendCode, arg.DiscordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DiscordID,
		&i.FriendCode,
	)
	return i, err
}
